export interface AfterDonationData {
  idAfterDonation: string;
  infectiousDiseasesChecked: boolean;
  isBloodUsable: boolean;
  note: string;
  status: string;
  healthCheckId: string;
  bloodId: string;
}

export interface BloodBag {
  bagId: string | null; // Will be auto-generated by backend
  volume: number;
  collectedDate: string;
  expirationDate: string;
  status: string;
  componentId: string;
  quantity: number;
  bloodCode: string;
}

export interface ManualSeparateData {
  afterDonationIds: string[];
  bloodBags: BloodBag[];
}

export interface ManualSeparateRequest {
  afterDonationIds: string[];
  bloodBags: {
    bloodCode: string;
    componentId: string;
    volume: number;
    quantity: number;
    collectedDate: string;
  }[];
}
