# ====== Server Port for Render ======
server.port=${PORT:8080}


# ====== MySQL connection ======
spring.datasource.url=jdbc:mysql://root:nBIcbCzWEHzuertsTiRjOYJbVsrsggNz@crossover.proxy.rlwy.net:23245/railway?serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=nBIcbCzWEHzuertsTiRjOYJbVsrsggNz

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ====== Mail Config ======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pphan2478@gmail.com
spring.mail.password=ckgl cnuw zutr umtd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.confirmation.base-url=https://swp391-su25.onrender.com/api/blood-requests/confirm

# ====== JWT Secret ======
jwt.secret=BloodCareSuperSecretKey2025@Project!!!

# B?t full l?i t? Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# B?t l?i toàn h? th?ng Spring
logging.level.org.springframework=DEBUG
logging.level.com.swp391=DEBUG

# B?t show stack trace
server.error.include-exception=true
server.error.include-message=always

spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.web.resources.static-locations=classpath:/static/,file:uploads/


# ====== Google ID Token Login ======
google.client.id=860417753548-va6oo146jl8imgk4qtdt40l5cfc30unk.apps.googleusercontent.com