import React, { useState, useEffect } from 'react';
import { useManualSeparate } from '../hooks/after-donation.hooks';
import { getAllBlood } from '../services/blood.services';
import { getAllComponents } from '../services/components.services';
import type { AfterDonationData, BloodBag, ManualSeparateRequest } from '../types/after-donation.types';
import type { BloodData } from '../services/blood.services';
import type { ComponentData } from '../services/components.services';

interface ManualSeparateModalProps {
    isOpen: boolean;
    onClose: () => void;
    afterDonation: AfterDonationData;
    onSuccess: () => void;
    // Thêm prop để lấy dữ liệu mới nhất
    refreshedAfterDonationData?: AfterDonationData[];
}

const ManualSeparateModal: React.FC<ManualSeparateModalProps> = ({
    isOpen,
    onClose,
    afterDonation,
    onSuccess,
    refreshedAfterDonationData
}) => {
    const { loading, error, separateBlood, clearError } = useManualSeparate();
    const [bloodData, setBloodData] = useState<BloodData[]>([]);
    const [componentData, setComponentData] = useState<ComponentData[]>([]);
    const [numberOfBagsToAdd, setNumberOfBagsToAdd] = useState<number>(1);
    
    // Sử dụng dữ liệu mới nhất nếu có
    const currentAfterDonation = refreshedAfterDonationData?.find(
        item => item.idAfterDonation === afterDonation.idAfterDonation
    ) || afterDonation;
    const [bloodBags, setBloodBags] = useState<BloodBag[]>([{
        bagId: '', // Will be auto-generated by backend
        volume: 60, // Default to 60ml
        collectedDate: new Date().toISOString().split('T')[0], // Default to today
        expirationDate: '', // Will be auto-calculated by backend
        status: 'VALID', // Auto-set by backend
        componentId: '',
        quantity: 1,
        bloodCode: ''
    }]);

    // Fetch blood data and components data
    useEffect(() => {
        const fetchData = async () => {
            try {
                const [bloodDataResponse, componentDataResponse] = await Promise.all([
                    getAllBlood(),
                    getAllComponents()
                ]);
                setBloodData(bloodDataResponse);
                setComponentData(componentDataResponse);
            } catch (error) {
                console.error('Failed to fetch data:', error);
            }
        };
        
        if (isOpen) {
            fetchData();
        }
    }, [isOpen]);

    const volumeOptions = [
        { value: 60, label: '60ml' },
        { value: 125, label: '125ml' },
        { value: 200, label: '200ml' },
        { value: 250, label: '250ml' },
        { value: 300, label: '300ml' },
        { value: 350, label: '350ml' },
        { value: 450, label: '450ml' },
        { value: 500, label: '500ml' }
    ];

    // Get volume options based on component type
    const getVolumeOptionsForComponent = (componentId: string) => {
        const component = componentData.find(c => c.componentId === componentId);
        if (!component) return volumeOptions;

        switch (component.type) {
            case 'Tiểu cầu':
                return [{ value: 60, label: '60ml' }];
            case 'Hồng cầu':
                return [
                    { value: 125, label: '125ml' },
                    { value: 200, label: '200ml' }
                ];
            case 'Huyết tương':
                return [
                    { value: 200, label: '200ml' },
                    { value: 300, label: '300ml' }
                ];
            case 'Toàn phần':
                return [
                    { value: 250, label: '250ml' },
                    { value: 350, label: '350ml' },
                    { value: 450, label: '450ml' }
                ];
            default:
                return volumeOptions;
        }
    };

    const handleAddBloodBag = () => {
        const newBags = Array.from({ length: numberOfBagsToAdd }, () => ({
            bagId: '', // Will be auto-generated by backend
            volume: 60, // Default to 60ml
            collectedDate: new Date().toISOString().split('T')[0], // Default to today
            expirationDate: '', // Will be auto-calculated by backend
            status: 'VALID', // Auto-set by backend
            componentId: '',
            quantity: 1,
            bloodCode: ''
        }));
        setBloodBags([...bloodBags, ...newBags]);
        setNumberOfBagsToAdd(1); // Reset về 1 sau khi thêm
    };

    const handleRemoveBloodBag = (index: number) => {
        if (bloodBags.length > 1) {
            setBloodBags(bloodBags.filter((_, i) => i !== index));
        }
    };

    const handleBloodBagChange = (index: number, field: keyof BloodBag, value: string | number) => {
        const updated = bloodBags.map((bag, i) => {
            if (i === index) {
                const updatedBag = { ...bag, [field]: value };
                
                // If component ID changed, reset volume to first available option for that component
                if (field === 'componentId' && typeof value === 'string') {
                    const volumeOptions = getVolumeOptionsForComponent(value);
                    if (volumeOptions.length > 0) {
                        updatedBag.volume = volumeOptions[0].value;
                    }
                }
                
                return updatedBag;
            }
            return bag;
        });
        setBloodBags(updated);
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        clearError();

        try {
            // Validate blood bags - check componentId, bloodCode, and collectedDate
            const validBags = bloodBags.filter(bag => 
                bag.componentId && bag.bloodCode && bag.collectedDate
            );

            if (validBags.length === 0) {
                throw new Error('Vui lòng thêm ít nhất một túi máu hợp lệ với Component ID, mã máu và ngày thu thập');
            }

            const data: ManualSeparateRequest = {
                afterDonationIds: [currentAfterDonation.idAfterDonation],
                bloodBags: validBags.map(bag => ({
                    bloodCode: bag.bloodCode,
                    componentId: bag.componentId,
                    volume: bag.volume,
                    quantity: bag.quantity,
                    collectedDate: bag.collectedDate
                }))
            };

            console.log('Sending data to manual separate:', data);
            console.log('Valid bags:', validBags);

            await separateBlood(data);
            onSuccess();
            onClose();
        } catch (err) {
            // Error is handled by the hook
            console.error('Manual separate error:', err);
            // Show error message to user
            if (err instanceof Error) {
                console.error('Error message:', err.message);
            }
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
                {/* Header */}
                <div className="bg-gradient-to-r from-purple-600 to-indigo-700 px-6 py-4 rounded-t-xl">
                    <div className="flex justify-between items-center">
                        <div className="flex items-center">
                            <div className="bg-white bg-opacity-20 rounded-lg p-2 mr-4">
                                <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
                                </svg>
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-white">Tách Máu Thủ Công</h2>
                                <p className="text-purple-100 text-sm mt-1">
                                    ID: {currentAfterDonation.idAfterDonation}
                                </p>
                            </div>
                        </div>
                        <button
                            onClick={onClose}
                            className="text-white hover:text-gray-200 transition-colors duration-200"
                        >
                            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                </div>

                {/* Form */}
                <form onSubmit={handleSubmit} className="p-6">
                    {/* After Donation Info */}
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-3 text-gray-800">Thông tin mẫu máu</h3>
                        <div className="bg-gray-50 p-4 rounded-lg">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                    <p className="text-sm text-gray-600">ID After Donation</p>
                                    <p className="font-medium text-gray-900">{currentAfterDonation.idAfterDonation}</p>
                                </div>
                                <div>
                                    <p className="text-sm text-gray-600">Health Check ID</p>
                                    <p className="font-medium text-gray-900">{currentAfterDonation.healthCheckId}</p>
                                </div>
                                <div>
                                    <p className="text-sm text-gray-600">Blood ID</p>
                                    <p className="font-medium text-gray-900">{currentAfterDonation.bloodId}</p>
                                </div>
                                <div>
                                    <p className="text-sm text-gray-600">Trạng thái</p>
                                    <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${
                                        currentAfterDonation.status === "COMPLETED"
                                            ? "bg-green-100 text-green-800"
                                            : currentAfterDonation.status === "SEPARATED"
                                            ? "bg-blue-100 text-blue-800"
                                            : currentAfterDonation.status === "PENDING"
                                            ? "bg-yellow-100 text-yellow-800"
                                            : "bg-red-100 text-red-800"
                                    }`}>
                                        {currentAfterDonation.status === "COMPLETED" ? "Hoàn thành" : 
                                         currentAfterDonation.status === "SEPARATED" ? "Đã tách" :
                                         currentAfterDonation.status === "PENDING" ? "Chờ xử lý" : "Đã hủy"}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Blood Bags Section */}
                    <div className="mb-6">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-lg font-semibold text-gray-800">Danh sách túi máu</h3>
                            {currentAfterDonation.status !== "SEPARATED" && (
                                <div className="flex items-center space-x-2">
                                    <input
                                        type="number"
                                        min="1"
                                        max="10"
                                        value={numberOfBagsToAdd}
                                        onChange={(e) => setNumberOfBagsToAdd(parseInt(e.target.value) || 1)}
                                        className="w-16 px-2 py-1 border border-gray-300 rounded text-sm text-center"
                                        title="Số lượng túi máu muốn thêm"
                                    />
                                    <button
                                        type="button"
                                        onClick={handleAddBloodBag}
                                        className="px-4 py-2 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors text-sm font-medium"
                                    >
                                        <svg className="w-4 h-4 mr-2 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                                        </svg>
                                        Thêm {numberOfBagsToAdd > 1 ? `${numberOfBagsToAdd} túi` : 'túi máu'}
                                    </button>
                                </div>
                            )}
                        </div>

                        {bloodBags.map((bag, index) => (
                            <div key={index} className="border border-gray-300 rounded-lg p-4 mb-4 bg-gray-50">
                                <div className="flex justify-between items-center mb-4">
                                    <h4 className="font-semibold text-gray-800">Túi máu #{index + 1}</h4>
                                    {bloodBags.length > 1 && currentAfterDonation.status !== "SEPARATED" && (
                                        <button
                                            type="button"
                                            onClick={() => handleRemoveBloodBag(index)}
                                            className="text-red-500 hover:text-red-700 transition-colors"
                                        >
                                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                            </svg>
                                        </button>
                                    )}
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">
                                            Component ID <span className="text-red-500">*</span>
                                        </label>
                                        <select
                                            value={bag.componentId}
                                            onChange={(e) => handleBloodBagChange(index, 'componentId', e.target.value)}
                                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
                                            required={currentAfterDonation.status !== "SEPARATED"}
                                            disabled={currentAfterDonation.status === "SEPARATED"}
                                        >
                                            <option value="">Chọn Component ID</option>
                                            {componentData.map(component => (
                                                <option key={component.componentId} value={component.componentId}>
                                                    {component.componentId} - {component.type}
                                                </option>
                                            ))}
                                        </select>
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">
                                            Thể tích
                                        </label>
                                        <select
                                            value={bag.volume}
                                            onChange={(e) => handleBloodBagChange(index, 'volume', parseInt(e.target.value))}
                                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
                                            disabled={currentAfterDonation.status === "SEPARATED" || !bag.componentId}
                                        >
                                            {getVolumeOptionsForComponent(bag.componentId).map(option => (
                                                <option key={option.value} value={option.value}>
                                                    {option.label}
                                                </option>
                                            ))}
                                        </select>
                                        {!bag.componentId && (
                                            <p className="text-xs text-gray-500 mt-1">Chọn Component ID trước để xem các thể tích có sẵn</p>
                                        )}
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">
                                            Mã máu <span className="text-red-500">*</span>
                                        </label>
                                        <select
                                            value={bag.bloodCode}
                                            onChange={(e) => handleBloodBagChange(index, 'bloodCode', e.target.value)}
                                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
                                            required={currentAfterDonation.status !== "SEPARATED"}
                                            disabled={currentAfterDonation.status === "SEPARATED"}
                                        >
                                            <option value="">Chọn mã máu</option>
                                            {bloodData.map(blood => (
                                                <option key={blood.bloodCode} value={blood.bloodCode}>
                                                    {blood.bloodCode}
                                                </option>
                                            ))}
                                        </select>
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">
                                            Số lượng
                                        </label>
                                        <input
                                            type="number"
                                            value={bag.quantity}
                                            onChange={(e) => handleBloodBagChange(index, 'quantity', parseInt(e.target.value) || 1)}
                                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
                                            min="1"
                                            disabled={currentAfterDonation.status === "SEPARATED"}
                                        />
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">
                                            Ngày thu thập <span className="text-red-500">*</span>
                                        </label>
                                        <input
                                            type="date"
                                            value={bag.collectedDate}
                                            onChange={(e) => handleBloodBagChange(index, 'collectedDate', e.target.value)}
                                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
                                            required={currentAfterDonation.status !== "SEPARATED"}
                                            disabled={currentAfterDonation.status === "SEPARATED"}
                                        />
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* Error Display */}
                    {error && (
                        <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
                            <p className="text-red-600 text-sm">{error}</p>
                        </div>
                    )}

                    {/* Actions */}
                    <div className="flex justify-end space-x-3 pt-6 border-t border-gray-200">
                        <button
                            type="button"
                            onClick={onClose}
                            className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors font-medium"
                        >
                            {currentAfterDonation.status === "SEPARATED" ? "Đóng" : "Hủy"}
                        </button>
                        {currentAfterDonation.status !== "SEPARATED" && (
                            <button
                                type="submit"
                                disabled={loading}
                                className="px-6 py-2 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                {loading ? (
                                    <div className="flex items-center">
                                        <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                        </svg>
                                        Đang xử lý...
                                    </div>
                                ) : (
                                    'Tách máu'
                                )}
                            </button>
                        )}
                    </div>
                </form>
            </div>
        </div>
    );
};

export default ManualSeparateModal;
